// <auto-generated />
using System;
using AgriConnectPrototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriConnectPrototype.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511083504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriConnectPrototype.Models.FarmServiceRequest", b =>
                {
                    b.Property<int>("FarmServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmServiceRequestId"));

                    b.Property<decimal>("CostInZar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplyContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("UsdAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FarmServiceRequestId");

                    b.HasIndex("SupplyContractId");

                    b.ToTable("FarmServiceRequests");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.SupplyContract", b =>
                {
                    b.Property<int>("SupplyContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyContractId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("ProduceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAgreementPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplyContractId");

                    b.HasIndex("FarmerId");

                    b.ToTable("SupplyContracts");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.FarmServiceRequest", b =>
                {
                    b.HasOne("AgriConnectPrototype.Models.SupplyContract", "SupplyContract")
                        .WithMany("FarmServiceRequests")
                        .HasForeignKey("SupplyContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyContract");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.SupplyContract", b =>
                {
                    b.HasOne("AgriConnectPrototype.Models.Farmer", "Farmer")
                        .WithMany("SupplyContracts")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.Farmer", b =>
                {
                    b.Navigation("SupplyContracts");
                });

            modelBuilder.Entity("AgriConnectPrototype.Models.SupplyContract", b =>
                {
                    b.Navigation("FarmServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
